### ISSUE TITLE
Cannot change password. Missing API details

### ISSUE THREAD

**Issue by KHRifat** [SS88UK/enhance_password#1]
I encounter this error when attempting to reset my password: "Cannot change password. Missing API details."

**Comment by Neoboffin** [comment]
Morning @KHRifat,

This error means that the API details are missing in the config.inc.php for RoundCube. Could you check for them and let me know?

The plugin is looking for a key called `orchd_key` within the `$config` variable.

**Comment by KHRifat** [comment]
> Morning @KHRifat,
> 
> This error means that the API details are missing in the config.inc.php for RoundCube. Could you check for them and let me know?
> 
> The plugin is looking for a key called `orchd_key` within the `$config` variable.

I have solved the issue. Thanks for developing the plugin; it saved me time. If you had not developed it, I would have had to develop it myself.

**Comment by Neoboffin** [comment]
@KHRifat Glad you got it working!! Have a great week!

**Comment by KHRifat** [comment]
> Morning @KHRifat,
> 
> This error means that the API details are missing in the config.inc.php for RoundCube. Could you check for them and let me know?
> 
> The plugin is looking for a key called `orchd_key` within the `$config` variable.

I have solved the issue. Thanks for developing the plugin; it saved me time. If you had not developed it, I would have had to develop it myself.

**Comment by KHRifat** [comment]
> Morning @KHRifat,
> 
> This error means that the API details are missing in the config.inc.php for RoundCube. Could you check for them and let me know?
> 
> The plugin is looking for a key called `orchd_key` within the `$config` variable.

I have solved the issue. Thanks for developing the plugin; it saved me time. If you had not developed it, I would have had to develop it myself.

Appreciate your efforts.
